hyperparameters:
  BATCH_SIZE: 2
  NUM_EPOCHS: 50
  LEARNING_RATE: 0.0003
  WEIGHT_DECAY: 1e-5

model:
  INPUT_DIM: 80
  D_MODEL: 512
  NUM_HEADS: 8
  D_FF: 4096
  NUM_LAYERS: 8
  KERNEL_SIZE: 31
  DROPOUT: 0.15
  VOCAB_SIZE: 31
  EARLY_STOPPING_PATIENCE: 3
  NO_IMPROVE_EPOCHS: 0
